import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import './globals.css';

export const metadata = {
  title: {
    default: 'lego', // 如果没有title 则使用默认值
    template: '%s | lego', // 模板化
    // absolute: 'lego', // 绝对显示title
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
